<a href="https://colab.research.google.com/github/NijatLmmdv/-SLVMA/blob/main/Final_Last_version_no_padding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#main libraries
import numpy as np
from numpy.linalg import matrix_power


In [6]:
# Markov Chain
# from i state to j state in n steps

A = np.array([
    [.3, .4, .3],
    [.5, .2, .3],
    [.2, .1, .7]    
])
#212
i = 0
j = 2
n = 2

A = matrix_power(A, n)
print(A)

print("{: .7f}".format(A[i][j]))

[[0.35 0.23 0.42]
 [0.31 0.27 0.42]
 [0.25 0.17 0.58]]
 0.4200000


In [7]:
# Markov Chain - Stationary Distrubition

sd = np.array([
    [.3, .4, .3],
    [.5, .2, .3],
    [.2, .1, .7]    
])


prev = np.zeros((len(sd), len(sd))) 
copy = sd
c = 1

while((prev != sd).all()):
    prev = sd
    sd = np.dot(sd, copy)#multiply
    c+=1

print(sd,c)

[[0.29166667 0.20833333 0.5       ]
 [0.29166667 0.20833333 0.5       ]
 [0.29166667 0.20833333 0.5       ]] 41


In [8]:
#Flatten CNN

l = np.array([
    [1, .4, .3, .6, .8, .5, .6, .8, .3, .1],
    [1, .1, .5, .6, .7, .5, .9, .8, .3, .2],
    [1, .4, .7, .6, .8, .2, .9, .8, .3, .3],
    [1, .1, .5, .5, .7, .5, .9, .8, .3, .2],
    [0, .4, .5, .4, .8, .5, .4, .8, .3, .4],
    [0, .1, .3, .6, .7, .3, .9, .8, .3, .2],
    [0, .4, .5, .6, .8, .5, .9, .8, .3, .8],
    [0, .1, .5, .6, .8, .7, .1, .8, .3, .2],
    [0, .6, .5, .6, .8, .5, .9, .8, .3, .9],
    [0, .1, .5, .6, .7, .5, .9, .8, .3, .2]  
])
#matrix
def m_flttn(mtrx):
    r = np.array([])
    for i in range(len(mtrx)):
        r = np.insert(r, len(r), mtrx[i])
    return r

print(m_flttn(l))




[1.  0.4 0.3 0.6 0.8 0.5 0.6 0.8 0.3 0.1 1.  0.1 0.5 0.6 0.7 0.5 0.9 0.8
 0.3 0.2 1.  0.4 0.7 0.6 0.8 0.2 0.9 0.8 0.3 0.3 1.  0.1 0.5 0.5 0.7 0.5
 0.9 0.8 0.3 0.2 0.  0.4 0.5 0.4 0.8 0.5 0.4 0.8 0.3 0.4 0.  0.1 0.3 0.6
 0.7 0.3 0.9 0.8 0.3 0.2 0.  0.4 0.5 0.6 0.8 0.5 0.9 0.8 0.3 0.8 0.  0.1
 0.5 0.6 0.8 0.7 0.1 0.8 0.3 0.2 0.  0.6 0.5 0.6 0.8 0.5 0.9 0.8 0.3 0.9
 0.  0.1 0.5 0.6 0.7 0.5 0.9 0.8 0.3 0.2]


In [9]:
#Pooling

def m_plng(l, s, k):
    rows, cols = np.shape(l) #layerin olculeri

    r = int((rows - k)/s + 1) 
    cl = int((cols - k)/s + 1) 
    
    pooled_layer = np.zeros((r, cl))
    
    for i in range(r):
        for j in range(cl):
            # res = np.amax(layer[i:i+kernel, j:j+kernel])
            r = np.amin(l[i:i+k, j:j+k])
            # res = round(np.average(layer[i:i+kernel, j:j+kernel]), 2)
            pooled_layer[i][j] = r

    return pooled_layer

print(m_plng(l, 1, 3))       
        

[[0.1 0.1 0.3 0.2 0.2 0.2 0.3 0.1]
 [0.1 0.1 0.5 0.2 0.2 0.2 0.3 0.2]
 [0.  0.1 0.4 0.2 0.2 0.2 0.3 0.2]
 [0.  0.1 0.3 0.3 0.3 0.3 0.3 0.2]
 [0.  0.1 0.3 0.3 0.3 0.3 0.3 0.2]
 [0.  0.1 0.3 0.3 0.1 0.1 0.1 0.2]
 [0.  0.1 0.5 0.5 0.1 0.1 0.1 0.2]
 [0.  0.1 0.5 0.5 0.1 0.1 0.1 0.2]]


In [10]:
#conv2D
fl = np.array([
    [.1,.8,.6],
    [.5,.7,.5],
    [.2,.2,.8]
])


def manual_conv2D(layer, stride, fl):
    f_size = len(fl)
    rows, cols = np.shape(layer) #layerin olculerini aliriq
    
    r = int((rows - f_size)/stride + 1) # yeni layerin row sayisi
    cl = int((cols - f_size)/stride + 1) # yeni layerin column sayisi
    
    conv2d_layer = np.zeros((r, cl))
    
    for i in range(0, r, stride):
        for j in range(0, cl, stride):
            res = round(np.sum(np.dot(layer[i: i+f_size, j: j+f_size], fl)), 2)
            conv2d_layer[i][j] = res
    
    return conv2d_layer


print(manual_conv2D(l, 1, fl))







[[7.83 6.06 8.07 8.05 8.37 8.76 8.76 5.85]
 [7.56 5.83 8.08 7.73 8.58 9.27 9.21 5.97]
 [6.57 6.04 7.86 7.6  8.13 8.42 8.46 6.21]
 [4.08 4.91 7.14 7.55 8.15 8.57 8.46 6.09]
 [3.09 5.48 7.43 7.87 8.3  8.57 8.46 6.81]
 [2.58 5.27 7.77 8.41 8.28 8.36 8.01 6.57]
 [3.67 6.36 8.19 8.82 8.77 8.66 8.01 7.41]
 [3.16 5.91 8.07 8.65 8.62 8.66 8.01 6.69]]
